In [8]:
import numpy as np

In [10]:
matriz01 = np.array([[1,2,3],[4,5,6]])
matriz02 = np.array([[5,5,6],[3,8,4]])

print(matriz01)
print(matriz02)

[[1 2 3]
 [4 5 6]]
[[5 5 6]
 [3 8 4]]


In [14]:
# crie um método que receba duas matrizes, some os valores total de cada matriz e depois multiple o resultado 
#delas e retorne o valor.

def calculaMatriz(mtz01,mtz02):
  print(mtz01.sum() * mtz02.sum())

#Consome o Método
calculaMatriz(matriz01,matriz02)

651


In [29]:
#Exercício 03
#Criar uma matriz nxm (n = 5, m =7(colunas))
matriz03 = np.array([[1,2,3,4,5,6,7],[10,5,9,8,4,3,52],[0,2,5,9,7,1,11],[8,1,6,7,2,6,4],[2,5,8,3,6,9,1]])
#print(matriz03)

#faça a matriz transposta desta matriz
print(matriz03.T)

#somar toda matrix
print(matriz03.sum())

#somar todas as colunas
print(matriz03.sum(axis=0))

#somar todas as linhas.
print(matriz03.sum(axis=1))

#retorne o maior valor
print(matriz03.max())

#retorne o menor valor.
print(matriz03.min())

[[ 1 10  0  8  2]
 [ 2  5  2  1  5]
 [ 3  9  5  6  8]
 [ 4  8  9  7  3]
 [ 5  4  7  2  6]
 [ 6  3  1  6  9]
 [ 7 52 11  4  1]]
222
[21 15 31 31 24 25 75]
[28 91 35 34 34]
52
0


In [50]:
#4. Crie uma matriz nxn (n=5). Agora some essa matriz com a matriz do exercício 3.
matriz04 = np.array([[1,2,3,4,5],[10,5,9,8,4],[0,2,5,9,7],[8,1,6,7,2],[2,5,8,3,6]])
print(matriz04)
print(matriz04.sum()+matriz03.sum())


[[ 1  2  3  4  5]
 [10  5  9  8  4]
 [ 0  2  5  9  7]
 [ 8  1  6  7  2]
 [ 2  5  8  3  6]]
344


In [37]:
#5. crie um array de números que vai de 0 a 1000.
print(np.arange(0,1000))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [40]:
#6. crie uma matriz só de zeros.
np.zeros((3,3))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])